site_name: My Docs
theme:
  name: 'material'
nav:
  - Home: index.md
  - About: about.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true  # 启用通用TeX语法支持


extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-chtml-full.js
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-svg-full.js